### ISSUE TITLE
Overly specific compiler name checks

### ISSUE THREAD

**Issue by silentbicycle** [katef/kmkf#9]
The dependency generation in `dep.mk`, some of the `ASAN`/`UBSAN` rules, and probably other things fail in subtle ways if you set `CC` to a version-suffixed name, such as `clang-10`, because the makefile rules only compare against exactly "clang", "gcc", "emcc", and so on. They should probably be more flexible.

**Comment by katef** [comment]
Switched to `M:clang*` and friends in 118ea1fb076ab5706122f47be06a3b3535596f71. Will update kmkf for each repo to get their own local conditions.
